export const UserActionTypes = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  TOGGLE_ANNOUCEMENT: 'TOGGLE_ANNOUCEMENT',
  TOGGLE_GROUP_ANNOUCEMENT: 'TOGGLE_GROUP_ANNOUCEMENT',
  TOGGLE_USER_INFO: 'TOGGLE_USER_INFO',
};
