import Head from 'next/head';
import Main from '../components/main/main';
import { motion, AnimatePresence } from 'framer-motion';
import { selectCurrentUser } from '../src/store/user/user.selector';
import { useSelector } from 'react-redux';

import Landingmain from '../components/landing page/Landingmain';

export default function Home() {
  const user = useSelector(selectCurrentUser);

  return (
    <>
      <AnimatePresence key={user ? 'main' : 'SignIn'}>
        <Head>
          <title>ClassRoom</title>
          <meta
            name='description'
            content='Generated by create next app'
          />
          <meta
            name='viewport'
            content='width=device-width, initial-scale=1'
          />
          <link
            rel='icon'
            href='/favicon.ico'
          />
        </Head>
        <main className='min-h-screen'>{user ? <Main /> : <Landingmain />}</main>
      </AnimatePresence>
    </>
  );
}
