import Head from 'next/head';
import Link from 'next/link';
import Main from '../components/main';
import { selectCurrentUser } from '../src/store/user/user.selector';
import { useSelector } from 'react-redux';

export default function Home() {
  return (
    <>
      <Head>
        <title>ClassRoom</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1'
        />
        <link
          rel='icon'
          href='/favicon.ico'
        />
      </Head>
      <>
        <main
          className=' 
          min-h-screen flex flex-col-reverse sm:flex-col lg:flex-row dark:bg-gray-900 overflow-x-hidden
  '
        >
          <Main />
        </main>
      </>
    </>
  );
}
